apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring
      
  template:
    metadata:
      labels:
        app: spring
        tier: spring
    spec:
      containers:
        - name: spring
          image: rishi236/spring:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: hello


---
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: hello
    tier: hello
  type: LoadBalancer
