---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: rishi236/spring:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
  
metadata:
  name: spring
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
  - port: 5000
    targetPort: 5000
